#!/bin/bash
rm -rf output
HADOOP_VERSION="3.4.0" 
JAVA_VERSION="17.0.12"
export HADOOP_HOME="$HOME/hadoop-$HADOOP_VERSION"
export JAVA_HOME="$HOME/jdk-$JAVA_VERSION"
export PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_YARN_HOME=$HADOOP_HOME
export HADOOP_LOG_DIR=$HADOOP_HOME/logs
/bin/bash

